### PR TITLE
Issue templates added 

### LINKED ISSUE #173: Add Issue Templates
Hello Admins,
I want to add Issue Templates to this repo, please assign this issue to me.

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
closes #173 

cc @cosmicBboy

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
image

**Comment by MrKrishnaAgarwal** [comment]
cc @eapolinario

**Comment by MrKrishnaAgarwal** [comment]
Please approve @eapolinario or @cosmicBboy

**Comment by MrKrishnaAgarwal** [comment]
Please review @fg91 @eapolinario @cosmicBboy @sugatoray

**Review by cosmicBboy — APPROVED** [review]
thanks @MrKrishnaAgarwal !

**Comment by MrKrishnaAgarwal** [comment]
Thankyou @cosmicBboy
As I said in my previous pull request, it's not possible to fix the checks, as the whole format of the file will change.

Thanks for approving, please merge it soon :)

**Review by eapolinario — APPROVED** [review]

**Pull request merged**
