### PR TITLE
MNIST Tutorial Update

### LINKED ISSUE #189: [DOCS] Updating MNIST Tutorial
### What would you like to share?

The MNIST: Digits Classification Tutorial page currently only consist of codes to be run but does not mention what each line of code or function means nor their significance in the Model.

Suggestion:
I would suggest updating the tutorials page so that it can act as a step by step guide for new learners and help them understand use of each and every function and argument applied in the ML Code.

### Additional information

October-2022(Hacktoberfest)

### PR DESCRIPTION
**Pull request by Smartmind12**
Closes #189 

<a href="https://gitpod.io/#https://github.com/unionai-oss/unionml/pull/192"></a>

### CODE REVIEW

**Comment by eapolinario** [comment]
Please fix the lint errors by running `pre-commit run --all-files` at the root of the repo.

**Comment by Smartmind12** [comment]
> Please fix the lint errors by running `pre-commit run --all-files` at the root of the repo.

Thanks for the update will do the needful! Kindly add a hacktoberfest lable to it if possible…Thanks!!

**Comment by eapolinario** [comment]
> > Please fix the lint errors by running `pre-commit run --all-files` at the root of the repo.
> 
> Thanks for the update will do the needful! Kindly add a hacktoberfest lable to it if possible…Thanks!!

@Smartmind12 , the repo is already tagged with the `hacktoberfest` tag, so all PRs are automatically participating.

**Comment by Smartmind12** [comment]
> Please fix the lint errors by running `pre-commit run --all-files` at the root of the repo.

I tried it multiple times and i have fixed lin but i am getting this error :
Screenshot 2022-10-16 at 10 47 25 AM

**Comment by eapolinario** [comment]
@Smartmind12 , sorry you're having trouble with this. Please follow https://unionml.readthedocs.io/en/stable/contributing_guide.html#pre-commit-setup to be able to fix the errors caught by `pre-commit` locally.

**Comment by MrKrishnaAgarwal** [comment]
Hey @Smartmind12 and @eapolinario,
Can I make a duplicate pr of this with pre-commit fixed?

**Comment by Smartmind12** [comment]
> Hey @Smartmind12 and @eapolinario,
> Can I make a duplicate pr of this with pre-commit fixed?

Hey @MrKrishnaAgarwal I was busy past couple of days so i could not finish it but i have worked hard on it so i will rectify the precommit issue rightaway! So no need of duplicate PR!

**Comment by MrKrishnaAgarwal** [comment]
image
@Smartmind12 I can fix it!

**Comment by Smartmind12** [comment]
@eapolinario  All checks have passed in pre-commit in my local device, So kindly request you to merge the PR!

Screenshot_20221022_141608

**Comment by Smartmind12** [comment]
@eapolinario @cosmicBboy  Reminder to check this PR as i have already done with precommits...Thanks!

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
@Smartmind12 Lint is not fixed, you can see in the checks the lint is failing.
Kindly fix it else it will be difficult for maintainers to do that.
Else I can fix it =)

**Comment by MrKrishnaAgarwal** [comment]
#take

**Comment by Smartmind12** [comment]
> @Smartmind12 Lint is not fixed, you can see in the checks the lint is failing. Kindly fix it else it will be difficult for maintainers to do that. Else I can fix it =)

It is the is not lint error but the "myst markdown to jypter notebook" Conversion error for which i have already passed pre-commit on my local machine as shown in the above image as suggested by @eapolinario . So it is already completed!

**Pull request merged**
