### PR TITLE
Added COC and Contributing

### LINKED ISSUE #174: Add Code of conduct.md and Contributing.md
I will add  Code of conduct and Contributing to this repo.

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
Closes #174 

cc @cosmicBboy

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
Please approve @eapolinario or @cosmicBboy

**Comment by MrKrishnaAgarwal** [comment]
Please review @fg91 @eapolinario @cosmicBboy @sugatoray

**Comment by cosmicBboy** [comment]
hi @MrKrishnaAgarwal can you set up [pre-commit](https://unionml.readthedocs.io/en/stable/contributing_guide.html#pre-commit-setup) and run it locally? lint tests are failing

**Comment by MrKrishnaAgarwal** [comment]
> hi @MrKrishnaAgarwal can you set up [pre-commit](https://unionml.readthedocs.io/en/stable/contributing_guide.html#pre-commit-setup) and run it locally? lint tests are failing

Hi @cosmicBboy,
I tried doing that but the format of the files are changing.
I think it's not possible to fix, I'll try to but can you merge it without passing the checks?

**Comment by MrKrishnaAgarwal** [comment]
@cosmicBboy Approve the workflow plz

**Comment by MrKrishnaAgarwal** [comment]
Please merge this pr also: https://github.com/unionai-oss/unionml/pull/177

**Comment by MrKrishnaAgarwal** [comment]
@cosmicBboy checks are not running but they are successful

you can see here: https://github.com/MrKrishnaAgarwal/unionml/pull/1

**Comment by MrKrishnaAgarwal** [comment]
please merge this or now

ref: https://github.com/MrKrishnaAgarwal/unionml/pull/1

**Review by cosmicBboy — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
Thanks @cosmicBboy

**Pull request merged**
