### PR TITLE
Default Issue Template

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
It is used when someone creates a blank issue and doesn't choses any issue templates.

It's very helpful :)

cc @cosmicBboy

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
I have deleted config.yml file so that blank issues are enabled, and when someone creates a blank issue then this template will be used 😄

**Comment by MrKrishnaAgarwal** [comment]
@cosmicBboy and @eapolinario Please Review my PR's

**Comment by MrKrishnaAgarwal** [comment]
@cosmicBboy and @eapolinario Please Review my PR's

**Comment by MrKrishnaAgarwal** [comment]
#self-assign

**Review by eapolinario — APPROVED** [review]

**Comment by eapolinario** [comment]
Thank you, I agree this is a good idea.

**Comment by MrKrishnaAgarwal** [comment]
Thanks a lot 😄

**Pull request merged**
