### PR TITLE
Hyperlinking unionml logo with offical website.

### PR DESCRIPTION
**Pull request by Abubakrce19**
Now a user can go to unionml offical website with a single click. Minor but impactful.

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Open in Gitpod

<a href="https://gitpod.io/#https://github.com/unionai-oss/unionml/pull/196"></a>

### CODE REVIEW

**Review by MrKrishnaAgarwal — APPROVED** [review]
Looks good to me!
Thanks for contributing 👌

**Comment by Abubakrce19** [comment]
> Looks good to me! Thanks for contributing 👌

Thanks to you too

**Comment by Abubakrce19** [comment]
@MrKrishnaAgarwal 
Please merge this so i could be counted for swags

**Comment by MrKrishnaAgarwal** [comment]
> @MrKrishnaAgarwal Please merge this so i could be counted for swags

Sorry I don't have write access, I'm just a Contributor.
Tagging the maintainer: @eapolinario

**Comment by eapolinario** [comment]
> > @MrKrishnaAgarwal Please merge this so i could be counted for swags
> 
> 
> 
> Sorry I don't have write access, I'm just a Contributor.
> 
> Tagging the maintainer: @eapolinario 

Thanks for your contribution!

**Comment by Abubakrce19** [comment]
> 

Am i eligible for the swags now?

**Comment by MrKrishnaAgarwal** [comment]
> > 
> 
> Am i eligible for the swags now?

Yes. please fill this form: https://tally.so/r/nWO7qQ

**Comment by MrKrishnaAgarwal** [comment]
> > > @MrKrishnaAgarwal Please merge this so i could be counted for swags
> > 
> > 
> > Sorry I don't have write access, I'm just a Contributor.
> > Tagging the maintainer: @eapolinario
> 
> Thanks for your contribution!

Welcome 😊

**Pull request merged**
